---
Name: afterpay_routes
After: framework/routes#coreroutes
---

SilverStripe\Control\Director:
  rules:
    'afterpaypayment//$Action/$IDs': 'Sunnysideup\Afterpay\Control\AfterpayEcommercePaymentController'
